### ISSUE TITLE
Is Minecraft a proprietary protocol? Probabily yes? Move it.

### ISSUE THREAD

**Issue by CosminPerRam** [gamedig/rust-gamedig#119]
# What
Minecraft is technically a proprietary protocol, it may be for a very popular game which has a lot of versions (and query implementations), but it is still being used by one game, so compared to the other proprietary protocols, it would be appropriate to move it over.

# References
https://github.com/gamedig/rust-gamedig/blob/b584e11336862392df1c0d30b1f796366e4be518/src/protocols/types.rs#L19-L29

**Comment by Douile** [comment]
Maybe proprietary should be renamed, technically all protocols are proprietary software. Valve has documentation on how the query packets work but no (official) open-source implementation of the server or protocol. I think quake and gamespy are similar. The proprietary category currently is filled by protocols only used by one-specific game so maybe it could be something like `GameSpecificProtocol`, in that case I'm not sure if minecraft would be in it.

**Comment by CosminPerRam** [comment]
> Maybe proprietary should be renamed, technically all protocols are proprietary software. Valve has documentation on how the query packets work but no (official) open-source implementation of the server or protocol.

Agreed, maybe the word doesn't really fit to what it actually is.

> The proprietary category currently is filled by protocols only used by one-specific game so maybe it could be something like GameSpecificProtocol [...]

Sounds good, but lets drop the second mention of `Protocol`, so in the linked enum above that'll be `GAMESPECIFIC` (or `SPECIFIC` maybe?).

> [...] in that case I'm not sure if minecraft would be in it.

Why not? Although Minecraft has multiple versions and Java and Bedrock, its all the same game.
If Counter-Strike Source, Global Offsensive, Zombies, 1.6 were to have a (same) specific protocol (not the Valve one that they actually have) it would be the same thing to Minecraft, right? Still a protocol that applies to a specific game (in this example it would be `games`, because they are distinctively different to each other, but the same protocol applies to all of them, treating them like a single game).

**Comment by Douile** [comment]
> Sounds good, but lets drop the second mention of Protocol, so in the linked enum above that'll be GAMESPECIFIC (or SPECIFIC maybe?).

I like `GAMESPECIFIC`.

> Why not?

That makes sense, Minecraft should be in a `GAMESPECIFIC` category.
