### ISSUE TITLE
Decide on the wording of a "proprietary protocol".

### ISSUE THREAD

**Issue by CosminPerRam** [gamedig/rust-gamedig#154]
Said by @Douile in #119:
> I think quake and gamespy are similar. The proprietary category currently is filled by protocols only used by one-specific game so maybe it could be something like GameSpecificProtocol

**Comment by cainthebest** [comment]
Im going to close this as within v1 if a protocol is specific to 1 game the implementation should be within games module as it has no other use than the game it supports, this should get rid of the "proprietary" wording.
