### ISSUE TITLE
unused manifest key: workspace.name

### ISSUE THREAD

**Issue by CosminPerRam** [gamedig/rust-gamedig#170]
When running `cargo b`, the following warning yields:
`warning: <my local file path>\Cargo.toml: unused manifest key: workspace.name`.
This line was added in #126.

@cainthebest (referenced PR author) is this alright to remove?

**Comment by cainthebest** [comment]
It should be good to just remove that field as discussed in discord.

**Comment by cainthebest** [comment]
Fixed in #174
