### ISSUE TITLE
Bad ID tests

### ISSUE THREAD

**Issue by Douile** [gamedig/rust-gamedig#184]
Over on node the ID tests have encountered a few bugs: https://github.com/gamedig/node-gamedig/pull/496

# Bugs are as follows

- Rule 1 - fails to detect acronym:

```
IDFail {
    game_id: "cs2d",
    game_name: "CS2D",
    expected_id: "c2d",
    rule_stack: [
        NumbersAreTheirOwnWord,
        MoreThanTwoWordsMakeAcronym,
    ],
}
```

- Rule 8 - fails to use mod name when the mod name is parenthesized instead of dash separated:

`Halo Online (ElDewrito)` instead of `Halo Online - ElDewrito`.

```
IDFail {
    game_id: "eldewrito",
    game_name: "Halo Online ",
    expected_id: "haloonline",
    rule_stack: [
        TwoWordsOrLessUseFullWords,
    ],
}
```

---

There are also some IDs that would require rule changes to match how node currently has them:

- "IL-2 Sturmovik" -> "il2sturmovik"
  - rule 2 separates hyphenated words making this 3 words which becomes an acronym
- "James Bond 007: Nightfire" -> "jb007n"
  - rule 6 says only to use the first number

**Comment by podrivo** [comment]
Just fixed `Halo Online - ElDewrito`. Thanks for pointing it out! (:

**Comment by CosminPerRam** [comment]
This is done for a few weeks now.
For some possible context, see [node-gamedig#374](https://github.com/gamedig/node-gamedig/issues/374).
