### ISSUE TITLE
Packet Underflow 

### ISSUE THREAD

**Issue by cainthebest** [gamedig/rust-gamedig#26]
When using the lib to call this rust server a error is thrown.

![image](https://user-images.githubusercontent.com/75994858/225458239-13f4a4ec-a392-41dd-9d07-54632db8a98f.png)

**Comment by cainthebest** [comment]
This seems to be happening as a empty string was retuned within data and this caused `get_string_utf8()` to throw a `PacketUnderflow` error.
https://github.com/gamedig/rust-gamedig/blob/1b13d398567636f8f779f3d6d4b58fde0827bbd1/src/bufferer.rs#L96

**Comment by CosminPerRam** [comment]
Didn't had the time to look into it, but I'm almost sure it's because of the `get_string_utf8`, `get_string_utf8_unended` and/or `get_string_utf16` of the `Bufferer`.
When they have no data left, they throw this error (also happens for `u8`, `u16` and so on, but it's something that I also encountered on strings).
I'm not sure whether to remove this buffer size check completely or not (for strings).

**Comment by cainthebest** [comment]
When I did some debugging I was able to know that it is coming from 1 of those functions within `bufferer`. I think this can be confirmed as a bug. The issue maybe occurring on empty strings but that still unknown.

**Comment by CosminPerRam** [comment]
Not really a bug, calling one of those functions does not expect the buffer to be empty, maybe you want a get a string and you know that it must contain something (even only the `NULL` character, that's something).

**Comment by CosminPerRam** [comment]
An empty string (in UTF8 at least) is just `0x00` if I'm right.

**Comment by CosminPerRam** [comment]
As I'm working on #25 I encountered the same problem and I ended up creating another function, `get_string_utf8_optional` which if the buffer is empty, it returns an empty string.

Having a normal `get_string_utf8`, this `get_string_utf8_optional` and the additional `get_string_utf8_unended` when packets end with a string but they dont provide the final NULL byte, is a bit messy and I'll have to look into making this cleaner.

**Comment by cainthebest** [comment]
All of this makes a lot more sense and possibly `get_string` can just be a generic fn

**Comment by cainthebest** [comment]
@CosminPerRam what do you think of [this](https://github.com/cainthebest/rust-gamedig/blob/fix/bufferer/src/bufferer.rs) as a possible way to make it a it simpler

**Comment by CosminPerRam** [comment]
Looks really nice, I just have a small comment, would you make a PR?  we'll discuss thing over there.

**Comment by cainthebest** [comment]
I'm deviating from the example shown for prod use as it comes with shortfalls in protocol impl, Ill open a draft when I got something together.

**Comment by cainthebest** [comment]
Fixed in #62
