### ISSUE TITLE
Conditional protocol compilation

### ISSUE THREAD

**Issue by Douile** [gamedig/rust-gamedig#38]
It would be nice to be able to use feature flags to conditionally compile only a specific set of protocols (and/or games).

**Comment by CosminPerRam** [comment]
This is something that @cainthebest addressed over on the Discord server (invite link [here](https://discord.gg/NVCMn3tnxH)), this could totally be done, can't really say an exact date when this will be added, but for sure after the Q2 project goals are met.

**Comment by Douile** [comment]
> This is something that @cainthebest addressed over on the Discord server (invite link [here](https://discord.gg/NVCMn3tnxH)), this could totally be done, can't really say an exact date when this will be added, but for sure after the Q2 project goals are met.

Whoops, I had already written an implementation before you posted this. If it's too early to merge or isn't what you had in mind that's my bad.

**Comment by cainthebest** [comment]
@Douile I haven't yet got a imputation on it as ive been working on a primarily on longer term concept of this lib. feel free to open PRs as they will most likely be discussed before impl.

**Comment by cainthebest** [comment]
Took me quite a while to come up with a good and practical way of doing this, i will close this as completed for now as it has been implemented in #227 and will be expanded as more in the beta pre-release milestone.

Example:
https://github.com/gamedig/rust-gamedig/blob/74f8b8bfe42d8719a2361da4b206fbe38bace608/crates/lib/Cargo.toml#L46-L191
