### ISSUE TITLE
Issue with minecraft query

### ISSUE THREAD

**Issue by Douile** [gamedig/rust-gamedig#77]
While working on integration tests I noticed that Minecraft query doesn't work for popular servers such as `mc.hypixel.net`.

```
$ cargo run --example generic mc mc.hypixel.net
Querying 209.222.114.62 with game Game {
    name: "Minecraft",
    default_port: 25565,
    protocol: Minecraft(
        None,
    ),
}.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AutoQuery', examples/generic.rs:39:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Looking at the output of node-gamedig it succeeds with the "vanilla" protocol which is the equivalent of our java.

Using mc-java there is a packet underflow:

```
$ cargo run --example generic mc-java mc.hypixel.net
Querying 209.222.114.62 with game Game {
    name: "Minecraft (java)",
    default_port: 25565,
    protocol: Minecraft(
        Some(
            Java,
        ),
    ),
}.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PacketUnderflow', examples/generic.rs:39:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by CosminPerRam** [comment]
Hmmm, I do recall when I implemented it that some popular/big servers use some 'anti-ddos' solutions and some queries return with made up data/straight up doesn't work.
If you mentioned that it works with the `node` version, then yeah, this would probably would be a bug.

**Comment by Douile** [comment]
I believe they are using proxy software like https://papermc.io/software/velocity but i will have to test to confirm

**Comment by Douile** [comment]
Nevermind after looking into it I have found the issue. The difference between node and rust is that node sends the server address, while we use gamedig as the server address.

https://github.com/gamedig/rust-gamedig/blob/a4df444c86a305cc170200768c32e70b8a793ca2/src/protocols/minecraft/protocol/java.rs#L23-L24

Big servers (hypixel) will ignore the query if it doesn't have the correct server address.

The problem with this is that the server address needs to be the hostname of the server, in hypixels case `mc.hypixel.net`, but our query logic only passes IP address to the query function.

**Comment by Douile** [comment]
There are 2 solutions I can think of for this:

- For protocols that require unresolved host-names pass it in additional arguments like valve's GatherSettings
  - This gives caller complete control over what they specify
  - Requires caller to do DNS lookup themselves (they did before)
- Go back to passing `&str` or `impl ToSocketAddrs` instead of `IpAddr` for query giving the query function access to the pre-resolved host-name but also requiring us to do the lookup
  - `ToSocketAddrs` is the only way to do DNS lookups in std at the moment, but it requires a port to be included (hacky fix is to append ":0" if we are passed a string but that won't work if we implement generically)

**Comment by CosminPerRam** [comment]
Hey, coming back to this a bit late, I couldn't make a working version, I'll look into this a bit further.
Regarding the solutions, I do want to opt in for the 'additional arguments'.
