### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by Douile** [gamedig/rust-gamedig#78]
Adding issue templates will ensure that new issues follow the same format and can be created with  labels attached.

Examples of issue templates:
https://github.com/TeamNewPipe/NewPipe/tree/dev/.github/ISSUE_TEMPLATE

**Comment by CosminPerRam** [comment]
Thanks for the reminder that templates exist! Will look into it shortly.

**Comment by CosminPerRam** [comment]
Hey, I mention the issue in a PR i made about adding these templates, any opinions?
