### ISSUE TITLE
[CI] Use labeller to automatically label PRs

### ISSUE THREAD

**Issue by Douile** [gamedig/rust-gamedig#96]
**What is this feature about?**
The name prefix (`[CI] ...`) could be used to automatically add labels to PRs making them easier to filter.

**Additional context/references**
[labeler](https://github.com/actions/labeler) is an action made by Github that provides this functionality.

**Comment by CosminPerRam** [comment]
Feel free to reopen/do a pr if you think more automatic labels could be added.
