### ISSUE TITLE
Add matching aliases for node-gamedig games

### ISSUE THREAD

**Issue by Douile** [gamedig/rust-gamedig#98]
**What is this feature about?**
Some games (like garrysmod) are stored in the game definitions under a key (which was derived from the source file name) which differs from the key that was used in [node-gamedig]. It would be useful if there was either an alias in game definitions that matched the node-gamedig name or if the keys were changed to match node-gamedig.

**Additional context/references**
[List of node-gamedig games][node-gamedig-games]

[node-gamedig]: https://github.com/gamedig/node-gamedig
[node-gamedig-games]: https://github.com/gamedig/node-gamedig/blob/master/games.txt

**Comment by CosminPerRam** [comment]
We could just rename the keys to match node-gamedig.
I wouldn't want to have in game definitions as #38 (the games part of that pr) could solve this as well (having a key in the game definition).
